package clans;

import java.util.*;

public class DialogSelectTaxonomy extends javax.swing.JDialog {

    /**
     * 
     */
    private static final long serialVersionUID = -7657444211145106730L;
    /** Creates new form selecttaxdialog */
    public DialogSelectTaxonomy(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane1 = new javax.swing.JScrollPane();
        altlist = new javax.swing.JList(inarr);
        jPanel1 = new javax.swing.JPanel();
        okbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        altlist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(altlist);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout());

        okbutton.setText("OK");
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(okbutton);

        cancelbutton.setText("CANCEL");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelbutton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        //get the String currently selected in the list
        int selint=altlist.getSelectedIndex();
        rettax=scilist.get(selint);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okbuttonActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        // just exit
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelbuttonActionPerformed

    /**
    * @param args the command line arguments
    */
    //public static void main(String args[]) {
    //    java.awt.EventQueue.invokeLater(new Runnable() {
    //        public void run() {
    //            selecttaxdialog dialog = new selecttaxdialog(new javax.swing.JFrame(), true);
    //            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    //                public void windowClosing(java.awt.event.WindowEvent e) {
    //                    System.exit(0);
    //                }
    //            });
    //            dialog.setVisible(true);
    //        }
    //    });
    //}

    public static String gettax(javax.swing.JFrame parent, ArrayList<String> inlist, ArrayList<String> inscilist){
        scilist=inscilist;
        inarr=new String[inlist.size()];
        for(int i=inlist.size();--i>=0;){
            inarr[i]=inlist.get(i)+" ["+scilist.get(i)+"]";
        }//end for i
        new DialogSelectTaxonomy(parent).setVisible(true);
        return rettax;
    }

    static ArrayList<String> scilist=null;
    static String[] inarr=null;
    static String rettax=null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList altlist;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okbutton;
    // End of variables declaration//GEN-END:variables

}
