/*
 * showsequences.java
 *
 * Created on June 1, 2004, 2:37 PM
 */
package clans;
/**
 *
 * @author  tancred
 */
public class showsequences extends javax.swing.JDialog {
    
    /** Creates new form showsequences */
    public showsequences(java.awt.Frame parent, StringBuffer indata) {
        super(parent, false);
        this.setTitle("Sequence window");
        initComponents();
        textarea.setText(indata.toString());
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 400));
        jScrollPane1.setViewportView(textarea);

        getContentPane().add(jScrollPane1);

        pack();
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    //    new showsequences(new javax.swing.JFrame(), true).show();
    //}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textarea;
    // End of variables declaration//GEN-END:variables
    
}
