package clans;

public class WindowFontChoice extends javax.swing.JDialog {

    /**
     * 
     */
    private static final long serialVersionUID = 7404540807325185729L;

    public WindowFontChoice(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle(titlestring);
        java.awt.GraphicsEnvironment gEnv =java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment();
        fontnames = gEnv.getAvailableFontFamilyNames();
        String[] tmp={"PLAIN","BOLD","ITALIC","BOLD&ITALIC"};
        stylearr=tmp;
        String[] tmpint={"8","10","12","14","16","20"};
        intarr=tmpint;
        initComponents();
        //now set the default to the current font selection
        int fontsize=retfont.getSize();
        String myfontname=retfont.getName();
        int fontstyle=retfont.getStyle();
        for (int i = fontnames.length - 1; i >= 0; i--) {
            if(myfontname.equalsIgnoreCase(fontnames[i])){
                fontComboBox.setSelectedIndex(i);
                break;
            }
        }
        sizecombobox.setSelectedItem(String.valueOf(fontsize));
        StyleComboBox.setSelectedIndex(fontstyle);
        changefont();
        repaint();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        fontlabel = new javax.swing.JLabel();
        sizelabel = new javax.swing.JLabel();
        stylelabel = new javax.swing.JLabel();
        fontComboBox = new  javax.swing.JComboBox(fontnames);
        sizecombobox = new javax.swing.JComboBox(intarr);
        StyleComboBox = new javax.swing.JComboBox(stylearr);
        jTextArea1 = new javax.swing.JTextArea();
        buttonpanel = new javax.swing.JPanel();
        okbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(0, 3));

        fontlabel.setText("Font");
        jPanel1.add(fontlabel);

        sizelabel.setText("Size");
        jPanel1.add(sizelabel);

        stylelabel.setText("Style");
        jPanel1.add(stylelabel);

        fontComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontComboBoxActionPerformed(evt);
            }
        });

        jPanel1.add(fontComboBox);

        sizecombobox.setEditable(true);
        sizecombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizecomboboxActionPerformed(evt);
            }
        });

        jPanel1.add(sizecombobox);

        StyleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StyleComboBoxActionPerformed(evt);
            }
        });

        jPanel1.add(StyleComboBox);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jTextArea1.setText("abcdefghijklmnopqrstuvwxyz\nABCDEFGHIJKLMNOPQRSTUVWXYZ\n1234567890\n-_=+!@#$%^&*()|\\/?.,';:'{}`~");
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextArea1, java.awt.BorderLayout.CENTER);

        buttonpanel.setLayout(new java.awt.GridLayout());

        okbutton.setText("OK");
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });

        buttonpanel.add(okbutton);

        cancelbutton.setText("Cancel");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        buttonpanel.add(cancelbutton);

        getContentPane().add(buttonpanel, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okbuttonActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        retfont=stdfont;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void sizecomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizecomboboxActionPerformed
        // Add your handling code here:
        try{
            size=java.lang.Integer.parseInt((String)sizecombobox.getSelectedItem());
        }catch(NumberFormatException e){}
        changefont();
        repaint();
    }//GEN-LAST:event_sizecomboboxActionPerformed

    private void fontComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontComboBoxActionPerformed
        // Add your handling code here:
        fontname=(String)fontComboBox.getSelectedItem();
        changefont();
        repaint();
    }//GEN-LAST:event_fontComboBoxActionPerformed

    private void StyleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StyleComboBoxActionPerformed
        // Add your handling code here:
        int retint=StyleComboBox.getSelectedIndex();
        if(retint==0){
            style=java.awt.Font.PLAIN;
        }else if(retint==1){
            style=java.awt.Font.BOLD;
        }else if(retint==2){
            style=java.awt.Font.ITALIC;
        }else{
            style=java.awt.Font.BOLD+java.awt.Font.ITALIC;
        }
        changefont();
        repaint();
    }//GEN-LAST:event_StyleComboBoxActionPerformed
        
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new WindowFontChoice(new javax.swing.JFrame(), true).setVisible(true);
    }
    
    static java.awt.Font retfont;
    static java.awt.Font stdfont;
    static String titlestring;
    static int size=10;
    static int style=java.awt.Font.PLAIN;
    static String fontname="Monospace";
    String[] fontnames;
    String[] stylearr;
    String[] intarr;
    
    /**
     * 
     * @param instring
     * @param infont
     * @return
     */
    public static java.awt.Font getfont(String instring,java.awt.Font infont){
        titlestring=instring;
        stdfont=infont;
        retfont=new java.awt.Font(infont.getAttributes());
        new WindowFontChoice(new javax.swing.JFrame(), true).setVisible(true);
        return retfont;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox StyleComboBox;
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JComboBox fontComboBox;
    private javax.swing.JLabel fontlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton okbutton;
    private javax.swing.JComboBox sizecombobox;
    private javax.swing.JLabel sizelabel;
    private javax.swing.JLabel stylelabel;
    // End of variables declaration//GEN-END:variables
    
    /**
     * 
     */
    public void changefont(){
        retfont = new java.awt.Font(fontname, style, size);
        jTextArea1.setFont(retfont);
        repaint();
    }
    
}
