package clans.gui;

import java.io.*;

import javax.swing.JFileChooser;

public class DialogSearchQueryEntry extends javax.swing.JDialog {
    
    /**
     * 
     */
    private static final long serialVersionUID = 9176398008906892605L;

    public DialogSearchQueryEntry(WindowShowSelectedSequences parent, boolean modal) {
        super(parent, modal);
        this.parent=parent;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        textpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        buttonpanel = new javax.swing.JPanel();
        okbutton = new javax.swing.JButton();
        loadbutton = new javax.swing.JButton();
        exactmatchcheck = new javax.swing.JCheckBox();
        clearbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textpanel.setPreferredSize(new java.awt.Dimension(50, 50));
        textpanel.setLayout(new javax.swing.BoxLayout(textpanel, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setViewportView(textarea);

        textpanel.add(jScrollPane1);

        getContentPane().add(textpanel, java.awt.BorderLayout.CENTER);

        buttonpanel.setLayout(new java.awt.GridLayout(1, 0));

        okbutton.setText("OK");
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });
        buttonpanel.add(okbutton);

        loadbutton.setText("Load File");
        loadbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadbuttonActionPerformed(evt);
            }
        });
        buttonpanel.add(loadbutton);

        exactmatchcheck.setText("Exact matches");
        buttonpanel.add(exactmatchcheck);

        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        buttonpanel.add(clearbutton);

        cancelbutton.setText("Cancel");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });
        buttonpanel.add(cancelbutton);

        getContentPane().add(buttonpanel, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        // return a null string
        retstr=null;
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // clear the textarea
        textarea.setText("");
        repaint();
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void loadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadbuttonActionPerformed
        String filename="no_name";
        try{
            javax.swing.JFileChooser fc=ClusteringWithGui.fc;
            int retval=fc.showOpenDialog(this);
            
            if(retval==JFileChooser.APPROVE_OPTION){
                File selectedfile=fc.getSelectedFile();
                filename=selectedfile.getAbsolutePath();
                BufferedReader inread=new BufferedReader(new FileReader(selectedfile));
                String inline;
                while((inline=inread.readLine())!=null){
                    textarea.append(inline+"\r\n");//Character.PARAGRAPH_SEPARATOR);
                    //tmpbuff.append(inline);
                }
                inread.close();
            }else{
                //the file loading was cancelled
                return;
            }
        }catch (IOException ioe){
            javax.swing.JOptionPane.showMessageDialog(this,"ERROR reading from "+filename);
            return;
        }
        //textarea.setText(tmpbuff.toString());
        repaint();
    }//GEN-LAST:event_loadbuttonActionPerformed

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        //concatenate all lines in the textarea and separate by two pipe symbols ("||") (used for the regexp search)
        StringBuffer tmpbuff=new StringBuffer();
        try{
            BufferedReader inread=new BufferedReader(new StringReader(textarea.getText()));
            String inline;
            if(exactmatchcheck.isSelected()){
                tmpbuff.append("^exact^ || ");
            }
            while((inline=inread.readLine())!=null){
                if(inline.trim().length()<1){
                    continue;
                }
                tmpbuff.append(inline+" || ");
            }
            inread.close();
        }catch (IOException ioe){
            javax.swing.JOptionPane.showMessageDialog(this,"IOERROR reading from textarea");
            return;
        }
        retstr=tmpbuff.toString();
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_okbuttonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    //    new getsearchtext(new javax.swing.JFrame(), true).show();
    //}
    
    public static String get(WindowShowSelectedSequences parent){
		new DialogSearchQueryEntry(parent,true).setVisible(true);
		return retstr;
    }
    

	static String retstr="";
    WindowShowSelectedSequences parent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JButton clearbutton;
    private javax.swing.JCheckBox exactmatchcheck;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadbutton;
    private javax.swing.JButton okbutton;
    private javax.swing.JTextArea textarea;
    private javax.swing.JPanel textpanel;
    // End of variables declaration//GEN-END:variables
    
}
